allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msw: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - deepmerge-ts@8.0.0
  - mysql2@3.22.0 || 3.23.1
  - vitest@4.1.11
  - "@vitest/mocker@4.1.11"
overrides:
  "@vitest/mocker@>=2.1.0 <4.1.11": ^4.1.11
  deepmerge-ts@<8.0.0: ^8.0.0
  mysql2@<3.22.0: ^3.22.0
  mysql2@<=3.23.0: ^3.23.1
  vitest@>=2.1.0 <4.1.11: ^4.1.11
